--- 
title: "m6a analysis"
author: "tsztank"
date: "`r format(Sys.time(), '%d/%B/%Y')`"
output:
  html_document:
    theme: journal
---

```{r knitr_options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  cache = T,
  autodep = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = NA,
  cache.path = 'cache/',
  fig.path = 'figures/')
```

```{r load_libraries, echo = F}
library(plyr)
library(tidyverse)
library(biomaRt)
library(magrittr)
library(yaml)
library(readr)
library(cowplot)
library(wesanderson)
library(GGally)
```

```{r get_gene_name_id_map, echo = F}
ensembl = useMart('ensembl', dataset = 'dmelanogaster_gene_ensembl')

genes <- ensembl %>%
	getBM(
		  attributes = c('ensembl_gene_id',
						 'ensembl_transcript_id',
						 'external_gene_name',
						 'external_transcript_name'),
		  mart = .) %>%
	as_tibble

colnames(genes) <- c('gene_id', 'tx_id', 'gene_name', 'tx_name') 
```

```{r load_kallisto_results, echo = F}
config = read_yaml('../../config.yaml')
samples <- config$samples

kallisto_dir = '../../data/kallisto_quant/'

kallisto_data <- samples %>% ldply(function(smpl){
		df <- read_table2(paste0(kallisto_dir, '/', smpl, '/abundance.tsv'))
		df$sample <- smpl

		df
	}) %>% 
	as_tibble %>%
	separate(sample, into = c('condition', 'replicate'), sep = '[_]') %>%
	rename(tx_id = target_id) %>%
	mutate(tx_id = as.factor(tx_id),
		   condition = as.factor(condition)) %>%
	left_join(genes, by = 'tx_id')
```

```{r plot_corr_between_runs, echo = F, eval = F}
kallisto_data %>%
	unite('run', condition, replicate) %>%
	dplyr::select(tx_id, run, tpm) %>%
	spread(run, tpm) %>%
	{
		ggpairs(., columns = 2:ncol(.))
	}
```

```{r plot_histogram_tpm, echo =F}
kallisto_data %>%
	ggplot(aes(tpm, fill = condition)) +
	geom_density(alpha = 0.8) +
	scale_x_log10() +
	scale_fill_manual(values=wes_palette(n=3, name="GrandBudapest1")) +
	ggtitle('TPM comparison between conditions')
```

```{r plot_histogram_counts, echo =F}
kallisto_data %>%
	ggplot(aes(est_counts, fill = condition)) +
	geom_density(alpha = 0.8) +
	scale_x_log10() +
	scale_fill_manual(values=wes_palette(n=3, name="GrandBudapest1")) +
	facet_grid(condition~replicate) +
	theme(axis.text.x = element_text(angle = 45, hjust =1)) +
	ggtitle('Estimated counts of each run')
```

```{r plot_genes_of_interest, echo = F}
genes_of_interest <- c('mbl', 'vri', 'Clk', 'tim')

kallisto_data %>%
	filter(gene_name %in% genes_of_interest) %>%
	group_by(gene_name, condition, replicate) %>%
	summarise(tpm = sum(tpm)) %>%
	ggplot(aes(gene_name, tpm, colour = condition, shape = replicate)) +
		geom_point(size = 4, position = position_dodge(width=0.3)) +
		scale_y_log10() +
		annotation_logticks(sides = 'l') +
		scale_colour_manual(values=wes_palette(n=3, name="GrandBudapest1"))
```

