samples:
  - IP_1_S26
  - IP_2_S29
  - IP_3_S32
  - IgG_1_S27
  - IgG_2_S30
  - IgG_3_S33
  - input_1_S25
  - input_2_S28
  - input_3_S31
dirs:
  data_out: 'data'
  reads: '/bardata1/inespatop/projects/michella/m6a/'
  annotations:
    bed: '/bardata1/inespatop/genomes/annotations/BED/dm6_ENS.bed'
