samples:
    ip_1: m6A_IP_1_S26_R2_001.fastq.gz
    ip_2: m6A_IP_2_S29_R2_001.fastq.gz
    ip_3: m6A_IP_3_S32_R2_001.fastq.gz
    igg_1: m6A_IgG_1_S27_R2_001.fastq.gz
    igg_2: m6A_IgG_2_S30_R2_001.fastq.gz
    igg_3: m6A_IgG_3_S33_R2_001.fastq.gz
    input_1: m6A_input_1_S25_R2_001.fastq.gz
    input_2: m6A_input_2_S28_R2_001.fastq.gz
    input_3: m6A_input_3_S31_R2_001.fastq.gz
reads_dir: /data/local/rajewsky/projects/kadener_collab/brandeis_secondment/m6a/
find_circ2_command: /home/tsztank/repos/find_circ2/find_circ.py
bt2_rRNA_index: /data/rajewsky/indices/dm6_rRNA_bowtie2_2.1.0/bt2_dm_rRNA
star_index: /data/rajewsky/indices/dm6_star_2.7.0/
bwa_index: /data/rajewsky/indices/dm6_bwa_0.7.12-r1039/dm6.fa
