links:
  transcriptomes:
    dm6: "ftp://ftp.ensembl.org/pub/release-95/fasta/drosophila_melanogaster/cds/Drosophila_melanogaster.BDGP6.cds.all.fa.gz" 
dirs:
  genome: '/bardata1/inespatop/genomes/raw/dm6/'
  tx: 'transcriptomes/'
  ix:
    kallisto: 'indices/kallisto/'
