downloads:
  transcriptomes:
    dm6: "ftp://ftp.ensembl.org/pub/release-95/fasta/drosophila_melanogaster/cds/Drosophila_melanogaster.BDGP6.cds.all.fa.gz" 
  annotations:
    dm6: 'ftp://ftp.ensembl.org/pub/release-95/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.95.gtf.gz'
  genomes:
    dm6: 'ftp://ftp.ensembl.org/pub/release-95/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.dna_sm.toplevel.fa.gz'
