transcriptomes:
    dm6: "/data/rajewsky/annotation/dm6/tophat_tx_index/ensGene.proper.fa"
annotations:
    dm6: "/data/rajewsky/annotation/dm6/tophat_tx_index/ensGene.proper.gff"
genomes:
    dm6: "/data/rajewsky/genomes/dm6/dm6.fa"
indices:
    dm6:
        star: "/data/rajewsky/indices/dm6_star_2.7.0/"
